config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'about' => 'main#about'
  get 'photo/index'
  get 'album/:id' => 'albums#show'
  get 'admin' => 'admin#index'
  post 'send_email' => 'main#send_email'
  get 'sitemap' => 'main#sitemap'

  namespace :admin do
    resources :sections
    resources :albums do
      resources :photos
    end
  end

  resources :message, only: [:create, :destroy]
  resources :discussion, only: [:index]
  resources :gallery, only: [:index, :show]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  mount Ckeditor::Engine => '/ckeditor'

  scope ':section/' do
    resources :articles, path: ''
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates_presence_of :name, :message => 'Название альбома не может быть пустым'
  has_one :discussion, as: :discussable
  has_many :photos

  before_create :create_discussion
  private
  def create_discussion
    self.discussion = Discussion.create
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :message => 'Загаловок не может быть пустым'
  validates_presence_of :content, :message => 'Содержание не может отсутствовать'
  validates_length_of :keywords, :maximum => 80, :message => 'Ключевые слова не могут превышать длину в 80 символов'
  before_create :create_discussion
  has_one :discussion, as: :discussable

  private
  def create_discussion
    self.discussion = Discussion.create
  end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :discussable, polymorphic: true
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :user, :content
  belongs_to :discussion
  belongs_to :user
  after_create :send_notification

  private
  def send_notification
    PhotoMailer.send_comment_notification(link: self.discussion.discussable).deliver_now
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :file, :styles => { :small => "200x200>", :medium => "600x600>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/

  before_create :save_to_end

  belongs_to :album
  belongs_to :article

  def save_to_end
    self.sort = 99999
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates_presence_of :name, :message => 'Название секции не может быть пустым'
  validates_presence_of :url, :message => 'Путь не может отсутствовать'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default users modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :validatable, :registerable

  def admin?
    self.role == 'admin'
  end
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < AdminController
  before_action :set_album, only: [:edit, :update, :destroy]

  def index
    @albums = Album.all
  end

  def edit
    @photos = @album.photos.order(:sort)
    @photos = {} unless @photos
  end

  def new
    @album = Album.new
  end

  def show
    id = params[:id]
    @photos = Album.find(id).photos
    render :layout => false
  end

  def create
    @album = Album.new(album_params)
    @photos = {}

      if @album.save
        redirect_to edit_admin_album_path @album
      else
        render :new, alert: 'Название альбома не может отсутствовать'
      end
  end

  def destroy
    @album.destroy
    redirect_to admin_path, notice: 'Альбом удален.'
  end

  def update

    result = @album.update(album_params)

    if request.xhr?
      if result
        render json: :ok
      else
        render json: :error
      end
      return
    end


    if result
      redirect_to albums_path, notice: 'Альбом успешно обновлен.'
    else
        render :edit
    end
  end

  private
    def set_album
      begin
        @album = Album.find(params[:id])
      rescue
        @album = Album.new
        flash.alert = 'Ошибка: некорректный индекс'
      end
    end

    def album_params
      params.require(:album).permit(:name, :cover)
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:edit, :update, :destroy]

  def index
    @albums = Album.all
  end

  def edit
    @photos = @album.photos.order(:sort)
    @photos = {} unless @photos
  end

  def new
    @album = Album.new
  end

  def show
    id = params[:id]
    @photos = Album.find(id).photos
    render :layout => false
  end

  def create
    @album = Album.new(album_params)
    @photos = {}

      if @album.save
        render :edit
      else
        render :new, alert: 'Название альбома не может отсутствовать'
      end
  end

  def destroy
    @album.destroy
    redirect_to admin_path, notice: 'Альбом удален.'
  end

  def update

    result = @album.update(album_params)

    if request.xhr?
      if result
        render json: :ok
      else
        render json: :error
      end
      return
    end


    if result
      redirect_to albums_path, notice: 'Альбом успешно обновлен.'
    else
        render :edit
    end
  end

  private
    def set_album
      begin
        @album = Album.find(params[:id])
      rescue
        @album = Album.new
        flash.alert = 'Ошибка: некорректный индекс'
      end
    end

    def album_params
      params.require(:album).permit(:name, :cover)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @page_keywords = keywords
    @page_description = description
  end

  def about
    @page_keywords = keywords
    @page_description = description
    @page_title = 'Всеволод Тоботрас. Об авторе'
  end

  def send_email
    PhotoMailer.send_message_to_author(params).deliver_now
    respond_to {|format| format.js }
  end

  def sitemap
    @sections = Section.all
    @articles = Article.all
    @albums = Album.all
  end

  private
  def keywords
    'Всеволод Тоботрас,фотография,фотошкола,путешествия,обучение,фотосъемка'
  end
  def description
    'Всеволод Тоботрас - профессиональный фотограф и преподаватель авторского курса фотографии'
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    @page_title || 'Всеволод Тоботрас. Художественная фотография'
  end

  def page_keywords
    @page_keywords || 'фото, фотография, художественная, фотошкола, фототур, фотоэкспедиция, обучение'
  end

  def page_description
    @page_description || 'Всеволод Тоботрас - профессиональная художественная фотография.
      Организация фотоэкспедиций и фототуров. Фотосъемка в студии, обучение художественной фотографии.'
  end

  def count_messages(entity_type, id)
    @discussion = Discussion.find_by about: entity_type, entity_id: id
  end

  def admin_signed_up?
    current_user && current_user.admin?
  end
end

app/helpers/article_helper.rb
module ArticleHelper
  def short_version
    params[:section] != 'news'
  end
end

app/helpers/discussion_helper.rb
module DiscussionHelper
  def owner_name(message)
    return message.user.nickname if message.user
    'Аноним'
  end

  def owner_email(message)
    return message.user.email if message.user
    ''
  end
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/travel_helper.rb
module TravelHelper
end

app/views/admin/albums/_form.html.erb
<% if @album.errors.any? %>
    <div class="alert alert-danger" role="alert">
      Не удалось сохранить альбом:
      <ul>
        <% @album.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for [:admin, @album], remote: render_for == 'edit', :html => {class: 'form-horizontal album-form'} do |f| %>

    <div class="form-group">
        <div class = 'row'>
          <div class = 'col-md-3'>
            <div class = 'input-group'>
                <span class="input-group-addon" id="sizing-addon1">Альбом</span>
              <%= f.text_field :name, class: 'col-sm-7 form-control' %>
            </div>
          </div>
          <div class = 'col-sm-8'>
            <% cmd = render_for == 'edit' ? 'Изменить название' : 'Сохранить' %>
            <%= f.submit cmd , remote: true, class: 'btn btn-primary btn-large' %>
            <%= link_to 'Вернуться', admin_path, class: 'btn btn-primary' %>
            <% if render_for == 'edit' %>
                <%= link_to 'Удалить', [:admin, @album], method: :delete, class: 'btn btn-danger', data: { confirm: 'Точно?'} %>
            <% end %>
          </div>
        </div>
    </div>

<% end %>

app/views/admin/albums/edit.html.erb
<% content_for :assets do %>
    <%= stylesheet_link_tag 'fileinput' %>
    <%= javascript_include_tag 'fileinput' %>
    <%= javascript_include_tag 'Sortable' %>
<% end %>

<div class = 'container album-container'>
    <div class = 'row'>
      <div class = 'col-md-12'>
        <%= render partial: 'form', locals: {render_for: 'edit'} %>
        <div class="form-group">
          <input id = "photo" type="file" name = 'file' multiple="true">
        </div>
      </div>
    </div>

  <div class = "row" id = 'drag-parent'>
    <% @photos.each do |pic| %>
        <div class = "col-sm-3 photo-container" data-id = '<%= pic.id %>'>
          <div class="thumbnail photo" id = 'photo-<%= pic.id %>'>
            <div class="img-container">
                <img src="<%= pic.file.url(:small) %>" class = 'photo'>
            </div>
            <div class="caption">
              <h4><%= pic.name %></h4>
              <p>
                <a class="btn btn-primary btn-sm" data-id = '<%= pic.id %>' role="button" data-toggle="modal" data-target="#myModal">Редактировать</a>
                <%= link_to 'Удалить', '', class: 'btn btn-danger btn-sm remove', data: { id: pic.id } %>
              </p>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <div>
    <a class="btn btn-primary save-order" role="button">Сохранить порядок следования фотографий</a>
  </div>

  <div class="modal fade large" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <span class="modal-title" id="myModalLabel">Фотография</span>
          <button class = 'btn btn-primary btn-sm' id = 'make-cover'>Сделать обложкой альбома</button>
        </div>
        <div class="modal-body thumbnail">
        </div>
        <div class="modal-footer">
          <div class="input-group input-group-lg">
            <span class="input-group-addon" id="sizing-addon1">Название</span>
            <input class="form-control" id = 'new-name' type="text" value="">
            <span class="input-group-btn">
                <button class = 'btn btn-success' id = 'change-name' data-dismiss="modal">Сохранить</button>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var photos = [];
  var uploadUrl = '<%= admin_album_photos_path @album %>';
  var albumId = <%= @album.id %>;

    <% @photos.each do | photo | %>
      photos['<%= photo.id %>'] = [];
      photos['<%= photo.id %>']['name'] = '<%= photo.name %>';
      photos['<%= photo.id %>']['medium'] = '<%= image_tag(photo.file.url(:medium))%>';
    <% end %>
</script>

app/views/admin/albums/index.html.erb
<div class = 'container'>
  <h1>Список альбомов</h1>

  <% if flash[:notice] %>
      <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% end %>

  <table class = "table table-hover">
    <thead>
    <tr>
      <th>Название</th>
    </tr>
    </thead>

    <tbody>
    <% @albums.each do |album| %>
        <tr>
          <td><%= album.name%></td>
          <td>
            <%= link_to 'Редактировать', edit_admin_album_path(album), {class: 'btn btn-primary'} %>
            <%= link_to 'Удалить', album, method: :delete, class: 'btn btn-danger', data: { confirm: 'Точно?'} %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Добавить альбом', new_admin_album_path, {class: 'btn btn-success'} %>
  <%= link_to 'Вернуться', admin_path, {class: 'btn btn-success'} %>

</div>

app/views/admin/albums/new.html.erb
<div class = 'container'>
  <div class="jumbotron admin-panel">
    <h2>Добавить альбом</h2>
    <%= render partial: 'form', locals: {render_for: 'new'} %>
  </div>
</div>

app/views/admin/albums/show.erb
<div class = 'album-container container'>
    <% @photos.each do |photo| %>
          <div class = 'album-photo col-sm-2'>
            <img src="<%= photo.file.url :small %>" alt=""/>
          </div>
    <% end %>
</div>