config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'about' => 'main#about'
  get 'photo/index'
  get 'album/:id' => 'albums#show'
  get 'admin' => 'admin#index'
  post 'send_email' => 'main#send_email'
  get 'sitemap' => 'main#sitemap'

  namespace :admin do
    resources :sections
    resources :albums do
      resources :photos
    end
  end

  resources :message, only: [:create, :destroy]
  resources :discussion, only: [:index]
  resources :gallery, only: [:index, :show]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  mount Ckeditor::Engine => '/ckeditor'

  scope ':section/' do
    resources :articles, path: ''
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates_presence_of :name, :message => 'Название альбома не может быть пустым'
  has_one :discussion, as: :discussable
  has_many :photos

  before_create :create_discussion
  private
  def create_discussion
    self.discussion = Discussion.create
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :message => 'Загаловок не может быть пустым'
  validates_presence_of :content, :message => 'Содержание не может отсутствовать'
  validates_length_of :keywords, :maximum => 80, :message => 'Ключевые слова не могут превышать длину в 80 символов'
  before_create :create_discussion
  has_one :discussion, as: :discussable

  private
  def create_discussion
    self.discussion = Discussion.create
  end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :discussable, polymorphic: true
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :user, :content
  belongs_to :discussion
  belongs_to :user
  after_create :send_notification

  private
  def send_notification
    PhotoMailer.send_comment_notification(link: self.discussion.discussable).deliver_now
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :file, :styles => { :small => "200x200>", :medium => "600x600>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/

  before_create :save_to_end

  belongs_to :album
  belongs_to :article

  def save_to_end
    self.sort = 99999
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates_presence_of :name, :message => 'Название секции не может быть пустым'
  validates_presence_of :url, :message => 'Путь не может отсутствовать'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default users modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :validatable, :registerable

  def admin?
    self.role == 'admin'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :validate_section_param!
  before_action :find_article, only: [:edit, :update, :destroy, :show]
  before_action :authenticate_admin!, only: [:new, :create, :update, :destroy, :edit]

  def index
    @articles = Article.where(section: @section).order(created_at: :desc)
    @articles = @articles.paginate page: params[:page], per_page: 10
    @page_title = 'Всеволод Тоботрас. ' + translate_section(@section)
    @page_keywords = keywords_for @section
    @page_description = description_for @section
  end

  def show
    @page_title = 'Всеволод Тоботрас. ' + @article.title
    @discussion = @article.discussion
    @page_keywords = @article.keywords
    @page_description = @article.description
  end

  def new
    @article = Article.new
    @action = 'create'
  end

  def create
    @article = Article.new(article_params.merge section: @section)
    if @article.save
      redirect_to action: 'index'
    else
      render action: 'new'
    end
  end

  def edit
    @action = 'update'
  end

  def update
    @article = Article.find(params[:id])
    if @article.update article_params
      redirect_to article_path id: @article.id
    else
      render action: 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def find_article
    @article = Article.find params[:id]
  end

  def article_params
    params.require(:article).permit(:title, :content, :keywords, :description)
  end

  def translate_section(section)
    {'travel' => 'Фотоэкспедиции', 'photography' => 'Фотосъемка',
     'teaching' => 'Фотошкола', 'news' => 'Новости',
     'publications' => 'Публикации'}[section]
  end

  def keywords_for(section)
    {'travel' => 'фотография,пейзаж,архитектура,репортаж,фотосъемка,Кавказ,сопровождение,маршруты',
     'teaching' => 'фотография,художественная,фотошкола,курсы,пейзаж,жанр,композиция,свет,обработка',
     'photography' => 'фотография,портрет,пейзаж,жанр,интерьер,архитектура,ученики,путешествие,Кавказ',
     'news' => 'статьи,фотокритика,портрет,пейзаж,репортаж,архитектура,интерьер,встречи',
     'publications' => 'фотография,художественная,методика,постобработка,Лайтрум,Фотошоп,рекомендации'}[section]
  end

  def description_for(section)
    {'travel' => 'Планирование фотоэкспедиций и фотографические отчеты о путешествиях',
     'teaching' => 'Обучение искусству фотографии, индивидуальные курсы по фотосъемке, композиции и постобработке',
     'photography' => 'Профессиональная съемка  в студии, на пленере, а также фотографическое сопровождение в экспедиции и копроративных мероприятий',
     'news' => 'Краткое изложение событий фотографической деятельности, информация о новых событиях и публикациях',
     'publications' => 'Информация и статьи в помощь начинающему и опытному фотографу'}[section]
  end

  def validate_section_param!
    @section = params[:section]
    valid_sections = %w( news teaching travel photography publications )
    not_found unless valid_sections.include? @section
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @page_keywords = keywords
    @page_description = description
  end

  def about
    @page_keywords = keywords
    @page_description = description
    @page_title = 'Всеволод Тоботрас. Об авторе'
  end

  def send_email
    PhotoMailer.send_message_to_author(params).deliver_now
    respond_to {|format| format.js }
  end

  def sitemap
    @sections = Section.all
    @articles = Article.all
    @albums = Album.all
  end

  private
  def keywords
    'Всеволод Тоботрас,фотография,фотошкола,путешествия,обучение,фотосъемка'
  end
  def description
    'Всеволод Тоботрас - профессиональный фотограф и преподаватель авторского курса фотографии'
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    @page_title || 'Всеволод Тоботрас. Художественная фотография'
  end

  def page_keywords
    @page_keywords || 'фото, фотография, художественная, фотошкола, фототур, фотоэкспедиция, обучение'
  end

  def page_description
    @page_description || 'Всеволод Тоботрас - профессиональная художественная фотография.
      Организация фотоэкспедиций и фототуров. Фотосъемка в студии, обучение художественной фотографии.'
  end

  def count_messages(entity_type, id)
    @discussion = Discussion.find_by about: entity_type, entity_id: id
  end

  def admin_signed_up?
    current_user && current_user.admin?
  end
end

app/helpers/article_helper.rb
module ArticleHelper
  def short_version
    params[:section] != 'news'
  end
end

app/helpers/discussion_helper.rb
module DiscussionHelper
  def owner_name(message)
    return message.user.nickname if message.user
    'Аноним'
  end

  def owner_email(message)
    return message.user.email if message.user
    ''
  end
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/travel_helper.rb
module TravelHelper
end

app/views/articles/_article.html.erb
<div class = "panel panel-default">
  <div class = 'panel-heading'>
    <%= link_to article_path id: article.id, section: article.section do %>
        <h3 class = "article-title"><%= article.title %></h3>
    <% end %>
    <div class = 'article-date title'><%= article.created_at.to_s[0..10] %></div>
  </div>
  <div class = 'panel-body'>
    <div class = "article-text <%= 'short' if short %>"><%= article.content.html_safe %></div>
    <%= link_to 'Читать дальше...', article_path(id: article.id, section: article.section), class: 'read-more' %>
    <hr/>
    <div class = 'social'>
      <a class="link btn-discuss" role="button" data-messages="<%= article.discussion.messages.count %>" data-id = '<%= article.discussion.id %>' data-toggle="modal" data-target="#discussion-modal">Обсудить <span class="badge"><%= article.discussion.messages.count %></span></a>
      <div class="fb-like" data-href="<%= root_url[0..-2] + article_path(section: article.section, id: article.id) %>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
    </div>
  </div>
</div>

app/views/articles/_discussionModal.erb
<div class="modal discussion fade large" id="discussion-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title">Комментарии</h3>
      </div>
      <div class="modal-body">
        <%= render partial: 'discussion/show' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/_form.erb
<% if @article.errors.any? %>
    <div class="alert alert-danger" role="alert">
      Не удалось сохранить статью:
      <ul>
        <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @article, url: {action: @action}, html:  {class: 'form-horizontal'} do |f| %>
    <div class="form-group">
      <div class="field">
        <%= f.label :title, 'Заголовок:', class: 'col-sm-1 control-label' %>
        <div class = 'col-sm-4'>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :content, 'Содержание:', class: 'col-sm-1 control-label' %>
        <div class = 'col-sm-11'>
          <%= f.cktext_area :content, :class => 'col-sm-11 form-control', :ckeditor => {:language => 'ru'} %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :keywords, 'Ключевые слова:', class: 'col-sm-1 control-label' %>
        <div class = 'col-sm-11'>
          <%= f.text_field :keywords, :class => 'col-sm-11 form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :description, 'Описание:', class: 'col-sm-1 control-label' %>
        <div class = 'col-sm-11'>
          <%= f.text_area :description, :class => 'col-sm-11 form-control' %>
        </div>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "Сохранить" , class: 'btn btn-success' %>
    </div>
<% end %>

app/views/articles/edit.erb
<div class="container admin-container">
  <h1>Редактировать статью</h1>
  <%= render :partial => 'form' %>
</div>

app/views/articles/edit.html.erb
<div class = 'container'>
  <div class="jumbotron">
    <h2>Редактирование новости</h2>
    <%= render 'form' %>
  </div>
  <%= link_to 'Вернуться', articles_path, class: 'btn btn-primary' %>
</div>

app/views/articles/index.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <div class = 'link articles-to-home'>
        <%= link_to root_path do %>
            <span class="glyphicon glyphicon-home"></span>
            На главную
        <% end %>
        </div>
    </div>
    <div class="col-xs-8 article article-scale">
      <% @articles.each do | article | %>
          <% @discussion = article.discussion %>
          <%= render partial: 'article', locals: {article: article, short: short_version} %>
      <% end %>
      <%= will_paginate @articles %>
    </div>
    <div class="col-md-2">
      <% if admin_signed_up? %>
          <%= link_to({action: 'new', section: @section}, {class: 'link-add-article btn btn-success btn-lg'}) do %>
              <span class="glyphicon glyphicon-plus"></span>
              Добавить статью
          <% end %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'discussionModal' %>

app/views/articles/index.html.erb
<div class = 'container admin-container'>
  <h1>Список новостей</h1>

  <% if flash[:notice] %>
      <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% end %>

  <table class = "table table-hover">
    <thead>
    <tr>
      <th>Заголовок</th>
      <th colspan="1"></th>
    </tr>
    </thead>

    <tbody>
    <% @articles.each do | article | %>
        <tr>
          <td><%= article.title%></td>
          <td>
            <%= link_to 'Редактировать', edit_article_path(article), {class: 'btn btn-primary'} %>
            <%= link_to 'Удалить', article, method: :delete, class: 'btn btn-danger', data: { confirm: 'Точно?'} %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Добавить новость', new_article_path, {class: 'btn btn-success'} %>
  <%= link_to 'Вернуться', admin_path, {class: 'btn btn-success'} %>
</div>

app/views/articles/new.erb
<div class="container admin-container">
    <h1>Добавить новую статью</h1>
    <%= render :partial => 'form' %>
</div>

app/views/articles/show.erb
<%= content_for :meta do %>
    <meta property="og:url"         content="<%= request.original_url %>" />
    <meta property="og:type"        content="article" />
    <meta property="og:title"       content="<%= @article.title %>" />
    <meta property="og:description" content="<%=  strip_tags @article.content %>" />
    <meta property="fb:app_id"      content="833150406780657" />
<% end %>

<div class='container-fluid'>
  <div class='side-links'>
    <div class='link side-link'>
      <%= link_to articles_path section: @article.section do %>
          <span class="glyphicon glyphicon-chevron-left"></span>
          Вернуться
      <% end %>
    </div>
    <div class='link side-link'>
      <%= link_to controller: 'main', action: 'index' do %>
          <span class="glyphicon glyphicon-home"></span>
          На главную
      <% end %>
    </div>
  </div>
  <div class = 'row'>
    <div class="col-sm-2">&nbsp;</div>
    <div class = 'article article-scale'>
      <% if admin_signed_up? %>
          <%= link_to( edit_article_path(id: @article.id), {class: 'link-edit-event btn btn-warning btn-lg'}) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Редактировать
          <% end %>
          <%= link_to( article_path(id: @article.id), {method: 'delete', data: { confirm: 'Точно?'}, class: 'link-edit-event btn btn-danger btn-lg'}) do %>
              <span class="glyphicon glyphicon-remove"></span>
              Удалить
          <% end %>
      <% end %>
      <%= render partial: 'article', locals: {article: @article, short: false} %>
    </div>
  </div>
</div>

<%= render partial: 'discussionModal' %>