config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'about' => 'main#about'
  get 'photo/index'
  get 'album/:id' => 'albums#show'
  get 'admin' => 'admin#index'
  post 'send_email' => 'main#send_email'
  get 'sitemap' => 'main#sitemap'

  namespace :admin do
    resources :sections
    resources :albums do
      resources :photos
    end
  end

  resources :message, only: [:create, :destroy]
  resources :discussion, only: [:index]
  resources :gallery, only: [:index, :show]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  mount Ckeditor::Engine => '/ckeditor'

  scope ':section/' do
    resources :articles, path: ''
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates_presence_of :name, :message => 'Название альбома не может быть пустым'
  has_one :discussion, as: :discussable
  has_many :photos

  before_create :create_discussion
  private
  def create_discussion
    self.discussion = Discussion.create
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :message => 'Загаловок не может быть пустым'
  validates_presence_of :content, :message => 'Содержание не может отсутствовать'
  validates_length_of :keywords, :maximum => 80, :message => 'Ключевые слова не могут превышать длину в 80 символов'
  before_create :create_discussion
  has_one :discussion, as: :discussable

  private
  def create_discussion
    self.discussion = Discussion.create
  end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :discussable, polymorphic: true
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :user, :content
  belongs_to :discussion
  belongs_to :user
  after_create :send_notification

  private
  def send_notification
    PhotoMailer.send_comment_notification(link: self.discussion.discussable).deliver_now
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :file, :styles => { :small => "200x200>", :medium => "600x600>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/

  before_create :save_to_end

  belongs_to :album
  belongs_to :article

  def save_to_end
    self.sort = 99999
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates_presence_of :name, :message => 'Название секции не может быть пустым'
  validates_presence_of :url, :message => 'Путь не может отсутствовать'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default users modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :validatable, :registerable

  def admin?
    self.role == 'admin'
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/article_helper.rb
module ArticleHelper
  def short_version
    params[:section] != 'news'
  end
end

app/helpers/discussion_helper.rb
module DiscussionHelper
  def owner_name(message)
    return message.user.nickname if message.user
    'Аноним'
  end

  def owner_email(message)
    return message.user.email if message.user
    ''
  end
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/travel_helper.rb
module TravelHelper
end

app/views/admin/index.html.erb
<div class = 'container-fluid'>
  <div class = 'row'>
    <div class = 'col-md-8'>
      <div class="jumbotron admin-panel">
        <h2>
          Альбомы:
          <a class="btn btn-success" href="<%= new_admin_album_path %>" role="button">Добавить альбом</a>
        </h2>
        <div class = 'row'>
        <% @albums.each do | album | %>
              <div class = 'album col-md-4'>
                <%= link_to edit_admin_album_path album do %>
                    <%= render partial: 'gallery/albumCard', locals: {album: album} %>
                <% end %>
              </div>
        <% end %>
        </div>
      </div>
    </div>
    <div class = 'col-md-4'>
      <div class="jumbotron admin-panel">
        <h2>Администрирование</h2>
        <p><a class="btn btn-primary btn-lg" href="<%= admin_sections_path %>" role="button">Редактировать секции сайта</a></p>
        <p><%= link_to('Выйти', destroy_user_session_path, method: 'delete', class: 'btn btn-primary btn-lg')  %></p>

        <!-- Yandex.Metrika informer -->
        <a href="https://metrika.yandex.ru/stat/?id=30930411&amp;from=informer"
           target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/30930411/3_0_ACB78EFF_ACB78EFF_0_pageviews"
                                               style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:30930411,lang:'ru'});return false}catch(e){}" /></a>
        <!-- /Yandex.Metrika informer -->
      </div>
    </div>
  </div>
</div>

app/views/layouts/_facebookInit.erb
<div id = 'fb-root'></div>
<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '833150406780657',
            xfbml      : true,
            version    : 'v2.3'
        });
    };

    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/_navbar.erb
<nav class="navbar navbar-inverse container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Всеволод Тоботрас</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <% @sections.each do | section | %>
          <li><a href = '<%=section.url%>'><%=section.name%></a></li>
      <% end %>
      <%= yield :controls %>
    </ul>
  </div>
</nav>

app/views/layouts/_yandexMetrika.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter30930411 = new Ya.Metrika({
                    id:30930411,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/30930411" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= page_title %></title>
    <meta name = 'keywords' content = '<%= page_keywords %>'>
    <meta name = 'description' content = '<%= page_description %>'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png">
    <meta http-equiv="content-language" content="ru">
    <meta charset="utf-8">

    <%= yield :meta %>
    <%= stylesheet_link_tag "application", params[:controller] %>
    <%= javascript_include_tag "application", params[:controller] %>
    <%= yield :assets %>

    <%= csrf_meta_tags %>
    <%= render 'layouts/yandexMetrika' %>
</head>
<body>
    <%= render 'layouts/facebookInit' %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
</body>
</html>

app/views/layouts/gallery.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <meta name = 'keywords' content = '<%= page_keywords %>'>
  <meta name = 'description' content = '<%= page_description %>'>
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="content-language" content="ru">
  <meta charset="utf-8">

  <%= yield :meta %>

  <%= stylesheet_link_tag "application", params[:controller] %>
  <%= javascript_include_tag "application", params[:controller] %>

  <%= yield :assets %>

  <%= csrf_meta_tags %>
  <%= render 'layouts/yandexMetrika' %>
</head>
<body>
<%= render 'layouts/facebookInit' %>

<%= yield %>

</body>
</html>