config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'about' => 'main#about'
  get 'photo/index'
  get 'album/:id' => 'albums#show'
  get 'admin' => 'admin#index'
  post 'send_email' => 'main#send_email'
  get 'sitemap' => 'main#sitemap'

  namespace :admin do
    resources :sections
    resources :albums do
      resources :photos
    end
  end

  resources :message, only: [:create, :destroy]
  resources :discussion, only: [:index]
  resources :gallery, only: [:index, :show]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  mount Ckeditor::Engine => '/ckeditor'

  scope ':section/' do
    resources :articles, path: ''
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates_presence_of :name, :message => 'Название альбома не может быть пустым'
  has_one :discussion, as: :discussable
  has_many :photos

  before_create :create_discussion
  private
  def create_discussion
    self.discussion = Discussion.create
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :message => 'Загаловок не может быть пустым'
  validates_presence_of :content, :message => 'Содержание не может отсутствовать'
  validates_length_of :keywords, :maximum => 80, :message => 'Ключевые слова не могут превышать длину в 80 символов'
  before_create :create_discussion
  has_one :discussion, as: :discussable

  private
  def create_discussion
    self.discussion = Discussion.create
  end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :discussable, polymorphic: true
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :user, :content
  belongs_to :discussion
  belongs_to :user
  after_create :send_notification

  private
  def send_notification
    PhotoMailer.send_comment_notification(link: self.discussion.discussable).deliver_now
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :file, :styles => { :small => "200x200>", :medium => "600x600>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/

  before_create :save_to_end

  belongs_to :album
  belongs_to :article

  def save_to_end
    self.sort = 99999
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates_presence_of :name, :message => 'Название секции не может быть пустым'
  validates_presence_of :url, :message => 'Путь не может отсутствовать'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default users modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :validatable, :registerable

  def admin?
    self.role == 'admin'
  end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < AdminController
  before_action :set_section, only: [:edit, :update, :destroy]

  def index
    @sections = Section.all
  end

  def edit
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      redirect_to admin_sections_path, notice: 'Секция успешно создана.'
    else
      render :new
    end
  end

  def destroy
    @section.destroy
    redirect_to admin_sections_path, notice: 'Секция удалена.'
  end

  def update
    if @section.update(section_params)
      redirect_to admin_sections_path, notice: 'Секция успешно обновлена.'
    else
      render :edit
    end
  end

  private
  def set_section
    begin
      @section = Section.find(params[:id])
    rescue
      @section = Section.new
      flash.alert = 'Ошибка: некорректный индекс'
    end
  end

  def section_params
    params.require(:section).permit(:name, :url)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @page_keywords = keywords
    @page_description = description
  end

  def about
    @page_keywords = keywords
    @page_description = description
    @page_title = 'Всеволод Тоботрас. Об авторе'
  end

  def send_email
    PhotoMailer.send_message_to_author(params).deliver_now
    respond_to {|format| format.js }
  end

  def sitemap
    @sections = Section.all
    @articles = Article.all
    @albums = Album.all
  end

  private
  def keywords
    'Всеволод Тоботрас,фотография,фотошкола,путешествия,обучение,фотосъемка'
  end
  def description
    'Всеволод Тоботрас - профессиональный фотограф и преподаватель авторского курса фотографии'
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:edit, :update, :destroy]

  def index
    @sections = Section.all
  end

  def edit
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      redirect_to sections_path, notice: 'Секция успешно создана.'
    else
      render :new
    end
  end

  def destroy
    @section.destroy
    redirect_to sections_path, notice: 'Секция удалена.'
  end

  def update
    if @section.update(section_params)
      redirect_to sections_path, notice: 'Секция успешно обновлена.'
    else
      render :edit
    end
  end

  private
  def set_section
    begin
      @section = Section.find(params[:id])
    rescue
      @section = Section.new
      flash.alert = 'Ошибка: некорректный индекс'
    end
  end

  def section_params
    params.require(:section).permit(:name, :url)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    @page_title || 'Всеволод Тоботрас. Художественная фотография'
  end

  def page_keywords
    @page_keywords || 'фото, фотография, художественная, фотошкола, фототур, фотоэкспедиция, обучение'
  end

  def page_description
    @page_description || 'Всеволод Тоботрас - профессиональная художественная фотография.
      Организация фотоэкспедиций и фототуров. Фотосъемка в студии, обучение художественной фотографии.'
  end

  def count_messages(entity_type, id)
    @discussion = Discussion.find_by about: entity_type, entity_id: id
  end

  def admin_signed_up?
    current_user && current_user.admin?
  end
end

app/helpers/article_helper.rb
module ArticleHelper
  def short_version
    params[:section] != 'news'
  end
end

app/helpers/discussion_helper.rb
module DiscussionHelper
  def owner_name(message)
    return message.user.nickname if message.user
    'Аноним'
  end

  def owner_email(message)
    return message.user.email if message.user
    ''
  end
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/travel_helper.rb
module TravelHelper
end

app/views/admin/sections/_form.html.erb
<% if @section.errors.any? %>
    <div class="alert alert-danger" role="alert">
      Не удалось сохранить альбом:
      <ul>
        <% @section.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for [:admin, @section], :html => {class: 'form-horizontal'} do |f| %>

    <div class="form-group">
      <div class="field">
        <%= f.label :name, 'Название:', class: 'col-sm-2 control-label' %>
        <div class = 'col-sm-8'>
          <%= f.text_field :name, class: 'col-sm-10 form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :url, 'Путь:', class: 'col-sm-2 control-label' %>
        <div class = 'col-sm-8'>
          <%= f.text_field :url, class: 'col-sm-10 form-control' %>
        </div>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "Сохранить" , class: 'btn btn-success' %>
    </div>

<% end %>

app/views/admin/sections/edit.html.erb
<div class = 'container'>
  <div class="jumbotron admin-panel">
    <h2>Редактирование секции</h2>
    <%= render 'form' %>
  </div>
  <%= link_to 'Вернуться', admin_sections_path, class: 'btn btn-primary' %>
</div>

app/views/admin/sections/index.html.erb
<div class = 'container admin-container'>
  <h1>Список секций</h1>

  <% if flash[:notice] %>
      <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% end %>

  <table class = "table table-hover">
    <thead>
    <tr>
      <th>Название</th>
      <th>Путь</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @sections.each do |section| %>
        <tr>
          <td><%= section.name%></td>
          <td><%= section.url%></td>
          <td>
            <%= link_to 'Редактировать', edit_admin_section_path(section), {class: 'btn btn-primary'} %>
            <%= link_to 'Удалить', admin_section_path(section), method: :delete, class: 'btn btn-danger', data: { confirm: 'Точно?'} %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Добавить секцию', new_admin_section_path, {class: 'btn btn-success'} %>
  <%= link_to 'Вернуться', admin_path, {class: 'btn btn-success'} %>
</div>

app/views/admin/sections/new.html.erb
<div class = 'container'>
  <div class="jumbotron admin-panel">
    <h2>Добавить секцию</h2>
    <%= render 'form' %>
  </div>
  <%= link_to 'Вернуться', admin_sections_path, class: 'btn btn-primary' %>
</div>

app/views/sections/_form.html.erb
<% if @section.errors.any? %>
    <div class="alert alert-danger" role="alert">
      Не удалось сохранить альбом:
      <ul>
        <% @section.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @section, :html => {class: 'form-horizontal'} do |f| %>

    <div class="form-group">
      <div class="field">
        <%= f.label :name, 'Название:', class: 'col-sm-2 control-label' %>
        <div class = 'col-sm-8'>
          <%= f.text_field :name, class: 'col-sm-10 form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :url, 'Путь:', class: 'col-sm-2 control-label' %>
        <div class = 'col-sm-8'>
          <%= f.text_field :url, class: 'col-sm-10 form-control' %>
        </div>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "Сохранить" , class: 'btn btn-success' %>
    </div>

<% end %>

app/views/sections/index.html.erb
<div class = 'container admin-container'>
  <h1>Список секций</h1>

  <% if flash[:notice] %>
      <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% end %>

  <table class = "table table-hover">
    <thead>
    <tr>
      <th>Название</th>
      <th>Путь</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @sections.each do |section| %>
        <tr>
          <td><%= section.name%></td>
          <td><%= section.url%></td>
          <td>
            <%= link_to 'Редактировать', edit_section_path(section), {class: 'btn btn-primary'} %>
            <%= link_to 'Удалить', section, method: :delete, class: 'btn btn-danger', data: { confirm: 'Точно?'} %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Добавить секцию', new_section_path, {class: 'btn btn-success'} %>
  <%= link_to 'Вернуться', admin_path, {class: 'btn btn-success'} %>
</div>